# tools/lib/citation.py
"""Generate citation metadata and export formats for proofs."""


def build_citation_context(
    proof_data: dict,
    canonical_url: str,
    slug: str,
    doi_data: dict | None,
) -> dict:
    """Build citation context from proof data and optional DOI sidecar."""
    generator = proof_data["generator"]
    date = generator["generated_at"]
    year = date[:4] if date else ""
    claim = proof_data["claim_natural"]
    title = f"Proof Engine Verification: {claim}"
    slug_sanitized = slug.replace("-", "_")

    doi = None
    concept_doi = None
    if doi_data:
        doi = doi_data.get("doi")
        concept_doi = doi_data.get("concept_doi")

    return {
        "title": title,
        "author": "Proof Engine",
        "year": year,
        "date": date,
        "url": canonical_url,
        "doi": doi,
        "concept_doi": concept_doi,
        "version": generator.get("version", ""),
        "verdict": proof_data.get("verdict", ""),
        "slug_sanitized": slug_sanitized,
        "repository": "https://github.com/yaniv-golan/proof-engine",
    }


def _bibtex_escape(text: str) -> str:
    """Escape special BibTeX characters."""
    return text.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")


def generate_bibtex(ctx: dict) -> str:
    """Generate BibTeX citation string."""
    lines = [
        f"@misc{{proofengine_{ctx['slug_sanitized']},",
        f"  title   = {{{_bibtex_escape(ctx['title'])}}},",
        f"  author  = {{{{Proof Engine}}}},",
        f"  year    = {{{ctx['year']}}},",
        f"  url     = {{{ctx['url']}}},",
        f"  note    = {{Verdict: {ctx['verdict']}. Generated by proof-engine v{ctx['version']}}},",
    ]
    if ctx["doi"]:
        lines.append(f"  doi     = {{{ctx['doi']}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate_ris(ctx: dict) -> str:
    """Generate RIS citation string."""
    lines = [
        "TY  - DATA",
        f"TI  - {ctx['title']}",
        "AU  - Proof Engine",
        f"PY  - {ctx['year']}",
        f"UR  - {ctx['url']}",
        f"N1  - Verdict: {ctx['verdict']}. Generated by proof-engine v{ctx['version']}",
    ]
    if ctx["doi"]:
        lines.append(f"DO  - {ctx['doi']}")
    lines.append("ER  -")
    return "\n".join(lines) + "\n"


def _identifier_url(ctx: dict) -> str:
    """Return the preferred identifier URL (DOI link or canonical URL)."""
    if ctx["doi"]:
        return f"https://doi.org/{ctx['doi']}"
    return ctx["url"]


def generate_apa(ctx: dict) -> str:
    """Generate APA citation string."""
    return f"Proof Engine. ({ctx['year']}). {ctx['title']}. {_identifier_url(ctx)}"


def generate_chicago(ctx: dict) -> str:
    """Generate Chicago citation string."""
    return f'Proof Engine. "{ctx["title"]}." {ctx["year"]}. {_identifier_url(ctx)}.'


def generate_cite_txt(ctx: dict) -> str:
    """Generate combined APA + Chicago citation text file."""
    return f"APA:\n{generate_apa(ctx)}\n\nChicago:\n{generate_chicago(ctx)}\n"
